---
- name: Instal compile  package
  sudo: true
  sudo_user: root
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - autoconf
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev

- name: Fetch chruby source
  sudo: true
  sudo_user: root
  get_url: "dest=/opt/chruby-{{ chruby_version }}.tar.gz url=https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz"
  changed_when: False

- name: Extract chruby source
  sudo: true
  sudo_user: root
  shell: "cd /opt && tar -xzvf /opt/chruby-{{ chruby_version }}.tar.gz"

- name: link chruby
  sudo: true
  sudo_user: root
  file: state=link src=/opt/chruby-{{ chruby_version }} path=/opt/chruby

- name: Install chruby
  sudo: true
  sudo_user: root
  template: src=chruby.sh dest=/etc/profile.d/chruby.sh mode=0644

- name: Fetch ruby-install source
  sudo: true
  sudo_user: root
  get_url: "dest=/opt/ruby-install-{{ ruby_install_version }}.tar.gz url=https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz"

- name: Extract ruby-install source
  sudo: true
  sudo_user: root
  shell: "cd /opt && tar -xzvf /opt/ruby-install-{{ ruby_install_version }}.tar.gz"
  changed_when: False

- name: link ruby-install
  sudo: true
  sudo_user: root
  file: state=link src=/opt/ruby-install-{{ ruby_install_version }} path=/opt/ruby-install

- name: install ruby-install
  sudo: true
  sudo_user: root
  shell: "cd /opt/ruby-install && make install"
  changed_when: False

- name: create rubies directory
  sudo: true
  sudo_user: root
  shell: "mkdir -p /opt/rubies"
  changed_when: False

- name: compile ruby
  sudo: true
  sudo_user: root
  shell: "CONFIGURE_OPTS='--disable-install-rdoc' /usr/local/bin/ruby-install ruby {{ruby_version}} --no-reinstall"
  changed_when: False
